name: Monica's Blog
description:
meta_description: "Monica's Blog"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://mbdimitrova.space'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://mbdimitrova.space'
author:         'Monica Dimitrova'
bio:            'Programmer, wannabe baker, tea drinker, cyberpunk enthusiast. INFJ'
